### ISSUE TITLE
[Feature] conduit build in the automated tests

### ISSUE THREAD

**Issue by keinou** [conduit-dart/conduit#86]
When updates occur, usually the build doesn't work, as a suggestion to predict, add the build in the tests

**Comment by j4qfrost** [comment]
This is actually what this test does https://github.com/conduit-dart/conduit/runs/5801100422?check_suite_focus=true

The issue is that some users may not have everything set up correctly (e.g. env variables) The CI itself caches the source into the $PUB_CACHE directory, which isn't how a normal user would usually access the directory.
