### ISSUE TITLE
'import of dart:mirrors is not supported' error when compiling to binary

### ISSUE THREAD

**Issue by atreeon** [conduit-dart/conduit#90]
How embedded is the use of mirrors in Conduit?

Binary compilation doesn't support 'mirrors'.

To recreate
 - Create Heroes project
 - run `dart compile exe bin/main.dart -o bin/main`
 - error received `import of dart:mirrors is not supported in the current Dart runtime`

**Comment by j4qfrost** [comment]
This is not a bug, it is inherent in the design of conduit. I have attempted to replace mirrors with reflectable to no avail. The meta programming for dart needs a rework before we can compile conduit directly. You can generate a binary with ```conduit build```, which copies the source and strips mirrors out in order to build the executable.

**Comment by atreeon** [comment]
@j4qfrost just out of interest can you please point me to the code that does the `conduit build` work?  (I can't seem to find it in the repo)

**Comment by atreeon** [comment]
Yes I was asking about how it strips the mirrors out. It seems quite complicated for me to understand after reading through that file but I'll give it another go.  I asked another question as I'm hoping to use the ORM code independently from Conduit.
(yup, re the edit, thank you, good advice)
